Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
clusters = unique(prediksi)
#create scatter plot for samples from each cluster
for cluster in clusters:
  #get indexes for samples with this cluster
  row_1x = where(yhat == cluster)
  pyplot_scatter(x_new[row_1x,0],x[row_1x,1])
pyplot.show
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-14-f4af402b9941>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mclusters[0m [0;34m=[0m [0munique[0m[0;34m([0m[0mprediksi[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;31m#create scatter plot for samples from each cluster[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfor[0m [0mcluster[0m [0;32min[0m [0mclusters[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m   [0;31m#get indexes for samples with this cluster[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m   [0mrow_1x[0m [0;34m=[0m [0mwhere[0m[0;34m([0m[0myhat[0m [0;34m==[0m [0mcluster[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'unique' is not defined
NameError: name 'unique' is not defined

